### PR TITLE
Added data required for WCSAxes

### PR DESCRIPTION
**Pull request by astrofrog**

### CODE REVIEW

**Comment by astrofrog** [comment]
@eteq - this follows your suggestion of separating out the data by object. I like it! Do we want to have a parent directory, e.g. `objects`? (to keep the top-level tidy)

**Comment by eteq** [comment]
@astrofrog - `objects` doesn't seem that necessary to me, as this isn't really intended for human consumption. I don't see much harm in the top-level having quite a few directories.

**Comment by astrofrog** [comment]
Ok, then feel free to review as-is

Also cc @cdeil

**Comment by eteq** [comment]
Looks just fine to me, @astrofrog (although I didn't look at the binaries). 

I'm not 100% sure the READMEs will show up right in the rendered github page, but we can just merge and see (and if not I can figure out how to fix it).

**Comment by astrofrog** [comment]
@eteq - I added the webhook to this repo so that when we merge a pull request, it will automatically ping the STScI server. I'll try it out now by merging this!

**Comment by eteq** [comment]
@astrofrog - it appears that the READMEs were _not_ copied over. This is because we don't want the base-level `README.md` of the repo to get copied over, but I couldn't figure out a way to exclude a specific file (as opposed to _all_ files named `README.md`).

Is that behavior we want, or not?  If the latter, we could either rename the other readmes, or maybe there's something tricky that could be done with jekyll/liquid.

**Comment by astrofrog** [comment]
@eteq - I think it's fine to just have the READMEs in the repository for now. The intent was just to make sure I documented what the files are _somewhere_. We can see in future if there's a way to include the meta-data on data.astropy.org.

**Pull request merged**
