### PR TITLE
Added Wise Observatory (Israel)

### PR DESCRIPTION
**Pull request by cylammarco**
### Description

This pull request adds Wise Observatory (Israel) to `sites.json`. `check_builtin_matches_remote()` passes without returning any messages.

### CODE REVIEW

**Comment by hamogu** [comment]
Thanks for helping us to improve the sites.json!
As part of quality control, I usually open the location in Google maps and check what I see - observatory domes are typically easy to spot. I noted that the coordinates given seem to be little off, see https://www.google.com/maps/@30.595833,34.763333,186m/data=!3m1!1e3 which is centered on the drive way about 150 m from  the domes. Do you know why that is?

(Google coordiantes typically match better than that, but I don't want to blindly apply an offset compared to an authorative source such as a manual.)

**Comment by cylammarco** [comment]
Hi @hamogu , I was copying the location from their manual. I agree it's off in Google Maps. I will look into this.

**Comment by cylammarco** [comment]
Hi @hamogu, I talked to the telescope manager, and this is his reply:

> Indeed in google maps the historical coordinates of 34:45:48 E and
> 30:35:45 N falls about 150-200 meters off-site towards the cliff. I
> guess that this inaccuracy is due to inaccuracies of the measurements
> done back at the 70's as you noted. Though, I guess that for all
> practical purposes it does not really matters.
> 
> Zooming in with google earth on the dome of the 1m telescope I get that
> the dome of the 1m telescope is at 34.76218 N and 30.59739 E, which
> correspond to 34:45:43.848 N and 30:35:50.604 E.  It also means that for
> each telescope at Wise one can get nowadays more accurate coordinates
> since the 1m, C28, C18, etc. each in a bit different place in the google
> map and one can get their precise coordinates just from there.
> 
> I guess that for now one can take for the 1m the coordinates from google
> earth.
> 

I have updated the coordinates to 34.76218 N and 30.59739 E. He said there is not any plan to update the web pages and documents about the coordinates any time soon. He would be happy to answer further questions: shaik@tauex.tau.ac.il

**Comment by hamogu** [comment]
That's good enough for me ;-)
Thanks!

**Pull request merged**
