### PR TITLE
Regenerate image tests for astropy/astropy#7098

### PR DESCRIPTION
**Pull request by lpsinger**
astropy/astropy#7098 apparently caused minor changes in many of the test images. This PR updates the baseline images.

### CODE REVIEW

**Comment by lpsinger** [comment]
Looks like the tick labels moved very very slightly.

**Comment by astrofrog** [comment]
@lpsinger - are you sure this is due to https://github.com/astropy/astropy/pull/7098? Can you try running the image tests without the changes? What version of Matplotlib and freetype are you using?

**Comment by lpsinger** [comment]
> @lpsinger - are you sure this is due to astropy/astropy#7098? Can you try running the image tests without the changes? What version of Matplotlib and freetype are you using?

This is what I did:

```
$ docker run -it ubuntu:xenial bash -l
# apt-get update
# apt-get -y build-dep python-astropy
# apt-get -y install git python3-pip
# pip3 install --upgrade pytest scipy
# pip3 install pytest-mpl
# git clone https://github.com/astropy/astropy
# cd astropy
# python3 setup.py test -P visualization.wcsaxes --remote-data -a '--mpl'
```

And indeed, it fails on master, without astropy/astropy#7098.

**Comment by astrofrog** [comment]
@lpsinger - ok, thanks for confirming! I need some time to figure out how to deal with these small changes and exactly which library upgrade is causing the differences.

**Comment by lpsinger** [comment]
OK, I regenerated the images with your docker images. Please try again.

**Pull request merged**
