### PR TITLE
Adding local copies of the intersphinx inverntories

### PR DESCRIPTION
**Pull request by bsipocz**
scipy.org is offline again, so about time to set up our copies of intersphinx inventories to have an option to fall back to in similar cases. Ironically we need to wait to get the scipy and numpy files (but merging this could wait until that happens).

### CODE REVIEW

**Comment by bsipocz** [comment]
@eteq - Can we add symlinks here? that would be great to avoid tracking versions in two packages.

**Comment by bsipocz** [comment]
This is good to go now.

**Comment by bsipocz** [comment]
@astrofrog, @eteq - Can we merge this? I'm opening helpers update PRs to the affiliates which only makes sense if this is merged.

**Comment by bsipocz** [comment]
@astrofrog @eteq - Could we please merge this? Today there was an outage with the mpl inventory and this backup was not available either: https://travis-ci.org/astropy/astropy-helpers/jobs/219019897#L697

**Comment by eteq** [comment]
I'm also not sure if symlinks work... but lets just try and see - can always back out if not.

**Pull request merged**
