### PR TITLE
Ignore file if it starts with an underscore

### PR DESCRIPTION
**Pull request by adrn**
This will make more sense in the context of a future issue or PR by me, but I'd like there to be a way to not index a file on the site. Here I've made it so files that start with an underscore are ignored.

### CODE REVIEW

**Comment by adrn** [comment]
Note: I haven't tested this because I don't have the actual server code so I can't render the template...

**Comment by astrofrog** [comment]
Seems reasonable to me! @eteq?

**Comment by eteq** [comment]
yep, looks fine - merging!

**Comment by eteq** [comment]
@adrn - FYI, a trick I've found for this is to push it up to your own _personal_ gh-pages branch.  Then adrn.github.io/astropy-data will contain the server-generated result.

**Comment by eteq** [comment]
@adrn - something in this cause the front page to be empty (as @astrofrog already noted), breaking the mirroring script.  While trying to fix that, I noticed that this PR didn't update the `file_index.json` file.  Of course that's understandable - it's silly to have to do both.  So I changed things in c4317fb7f21e03f5287ec6f05e5589bbcac73f24 to address that by making the table at the javascript level.  Unfortunately, that _also_ broke the mirroring script.  So I just had to rollback this PR completely in 437e74d39d7a760291db38e2aff94d38801ee4ba .

Moving forward, hopefully the javascript approach will work if we can change the server mirroring code to parse the JSON for links.  In the meantime, though, I did some quick tests (using the approach I described in the previous comment), and it looks like things with a leading underscore are _already_ ignored.  I think this is a jekyll feature, in that leading-underscore things are ignored as being jekyll-related configuration stuff...

**Pull request merged**
