### PR TITLE
New truths for visualization.wcsaxes

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to update "truths" for `astropy.visualization` tests for astropy/astropy#12032. I have tested that they work.

Screenshot 2021-08-25 172538

### CODE REVIEW

**Comment by pllim** [comment]
#yolo

**Comment by astrofrog** [comment]
Just to check, have you checked all the images to make sure there are no significant differences?

@Cadair - any idea why there were differences in the first place? I thought you said that with the matplotlib wheels the images should then be reproducible?

**Comment by pllim** [comment]
> no significant differences?

I see some axis labels jitter here and there. They don't seem significant to me but I cannot speak for everyone. Do I care if the rendered arcsec symbol jumps a little? Not really.

**Comment by pllim** [comment]
You can probably still look at artifacts at https://app.circleci.com/pipelines/github/astropy/astropy?branch=pull%2F12032 and see for yourselves before they get deleted by CircleCI.

**Pull request merged**
