### PR TITLE
Added SLALIB v2.5 sites from obs.f

### PR DESCRIPTION
**Pull request by scottransom**
I used a tiny little conversion script to make these using pyslalib.  Feel free to zap the duplicates, although these are more precise in almost every case (and include individual telescopes like each of the VLTs and the 2 Kecks).  And there are radio observatories!

### CODE REVIEW

**Comment by astrofrog** [comment]
@scottransom - thanks! Are there any license restrictions with this data?

**Comment by scottransom** [comment]
Shouldn't be.  The original obs.f file is GPL, but that doesn't apply to physical values.  And the only thing that is the same in this file as in the original are the official names of the observatories.

**Comment by astrofrog** [comment]
@scottransom - ok, thanks!

Pinging @bmorris3 @jberlanga @eteq @cdeil

**Comment by bmorris3** [comment]
Great! When this gets merged, I'll work on astropy/astroplan#121

**Comment by eteq** [comment]
I'm mostly happy with this except for the problem of duplicates.  Are we ok with there being two entries for e.g. "TOLOLO4M" and "ctio"?  I lean towards yes, but probably at least a few should be removed (an obvious case is Palomar, where the existing entry is for the 200 inch, and this new one is _also_ the 200-inch, but better precision.  There are probably others too, though.)

**Comment by scottransom** [comment]
I'm completely with you.  One of the reasons why I explicitly didn't remove any duplicates in the pull request is that since these two separate databases (IRAF and SLALIB) were used by quite a few people in earlier codes, I figured that they may already know the shortcut names (like "TOLOLO4M" or "ctio") for their telescopes of choice.  We could, of course, make both names aliases and use whatever we think makes the most sense....

**Comment by eteq** [comment]
@scottransom - Good point about the "muscle memory" situation.  I think I favor the alias solution, although note that the points I made in #7 and astropy/astropy#4285 are relevant here: we need to make sure the builtin site list is consistent with the remote one.

**Comment by eteq** [comment]
(Oh, and you might also want to use the function astropy/astropy#4285 adds, following the instructions from #9 to make sure that's currently the case in this PR.)

**Comment by scottransom** [comment]
@eteq I noticed a month or two ago that this was still sitting here without any progress (I found that out when I looked at the observatories available in the builtins).  What needs to happen to get this merged?  Is it just the use of check_builtin_matches_remote?

**Comment by astrofrog** [comment]
@scottransom - I think that's what @eteq was referring to - thanks!

**Comment by scottransom** [comment]
@eteq and @astrofrog  ok, I just fixed the conflict and checked the new entries with the check_builtin_matches_remote function and have no errors.  There are still duplicates, though, and I'm not sure the best way to handle them in this file.

**Comment by luojing1211** [comment]
This pull request is very helpful for our scintillometry pipeline development.  I would like to see it move forward. Is there anything I can help to make this happen? 
And @scottransom are those coordinate in the geodetic coordinate system. It would be cool if we can compare the ITRF coordinates with [TEMPO](https://github.com/nanograv/tempo/blob/master/obsys.dat)/[PINT ](https://github.com/nanograv/PINT/blob/master/pint/observatory/observatories.py)

**Comment by pllim** [comment]
Needs a **rebase** to resolve conflict.

**Comment by luojing1211** [comment]
@scottransom, do you want me to fix the conflict and make it work?

**Comment by scottransom** [comment]
Sure! I'm swamped the next few days, so go for it.  It has bugged me for a long time that this never went in...  Thanks, @luojing1211 !

**Pull request closed without merging**
