### PR TITLE
Add spectrumplot tutorial data cube to astropy-data

### PR DESCRIPTION
**Pull request by kakirastern**
For the `spectrumplot`tutorial to be added to Learn Astropy. The most important content here is the data cube fits file.

### CODE REVIEW

**Comment by bsipocz** [comment]
@kakirastern - I think only the fits file should end up in this reposity from this PR. Both the scripts and rst docs should live in the tutorials repo. Same for the image, or in fact best would be to not even store the image but generate on the spot.

**Comment by kakirastern** [comment]
Hi @bsipocz Agreed. Have removed all files except the FITS file for the data cube to be used in the `spectrumplot` tutorial in this PR.

**Comment by bsipocz** [comment]
Thanks for the quick follow-up.

I would like to see the review for the tutorial itself, in https://github.com/astropy/astropy-tutorials/pull/423, before merging the file into this repo.

Also, it doesn't have to be now, but squashing the two commits is favourable to keep the unrelated files out of the history.

**Comment by kakirastern** [comment]
Not a problem! Have just squashed the commits into one before I forget. I will probably get back to this PR once the PR astropy/astropy-tutorials#423 has been reviewed.

**Comment by bsipocz** [comment]
Thanks. Basically the main thing I need from that review that this is the ideal file for the purposes of the tutorial (and/or possible reuses for future tutorials)

**Comment by kakirastern** [comment]
Sure, will be careful to let the repo maintainers know. They are indeed aware that I have been working on the tutorial even though no review for it has been made yet.

**Comment by kakirastern** [comment]
Apologies for the delay, but we have had some protracted discussions regarding where to store the concerned data file for a new Learn Astropy tutorial for the past few weeks. As a decision has been reached in last week's Learn Astropy meeting, I will follow up on this soon after updating the code in the tutorial notebook to download the [temporary link](https://github.com/astropy/astropy-data/raw/216305a852b76d73a8240fb90ab167353d3d733b/tutorials/spectrumplot/CubeSpectrumPlotExample.fits) instead.

**Comment by eteq** [comment]
closed at request of the author - last SHA 216305a852b76d73a8240fb90ab167353d3d733b

**Pull request closed without merging**
