### PR TITLE
Update wcsaxes test images for https://github.com/astropy/astropy/pull/6361

### PR DESCRIPTION
**Pull request by lpsinger**
See astropy/astropy#6361

### CODE REVIEW

**Comment by astrofrog** [comment]
@lpsinger - which folder did you use to duplicate? (one of the changes I saw in the diff made me suspect maybe you used ``2016-05-04T10:26:13.545916``, but just wanted to check)

**Comment by lpsinger** [comment]
> @lpsinger - which folder did you use to duplicate? (one of the changes I saw in the diff made me suspect maybe you used 2016-05-04T10:26:13.545916, but just wanted to check)

Yes, I copied `2016-05-04T10:26:13.545916`.

**Comment by astrofrog** [comment]
@lpsinger - ah ok - in fact the other folder (the 2017... one) was the right one to copy - sorry about that! Could you re-do this PR with that folder instead? Thanks!

**Comment by lpsinger** [comment]
> @lpsinger - ah ok - in fact the other folder (the 2017... one) was the right one to copy - sorry about that! Could you re-do this PR with that folder instead?

Done.

**Comment by astrofrog** [comment]
Thanks! This is a nice visual improvement.

**Pull request merged**
