### PR TITLE
Adding the Teide Observatory on Tenerife

### PR DESCRIPTION
**Pull request by DeltiKron**
Hi, I added an entry for the observatory I work at. I tried to run the tests listed in the coordinates readme but I got a numpy error in the testing. The error also occurred without my additions, so I'm not 100% sure whether it matters or I just don't have the correct environment to run the test...

Anyway, I'd be happy to have the request accepted and if I need to modify my environment and run the tests again in order to get it accepted, I'd be happy to do that as well.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-f596e8f6fd18> in <module>
      2 
      3 
----> 4 test_sites.check_builtin_matches_remote('sites.json')

~/anaconda3/envs/sdc/lib/python3.7/site-packages/astropy/coordinates/tests/test_sites.py in check_builtin_matches_remote(download_url)
    153         in_dl[name] = name in dl_registry
    154         if in_dl[name]:
--> 155             matches[name] = quantity_allclose(builtin_registry[name], dl_registry[name])
    156         else:
    157             matches[name] = False

~/anaconda3/envs/sdc/lib/python3.7/site-packages/astropy/units/quantity.py in allclose(a, b, rtol, atol, **kwargs)
   1760     """
   1761     return np.allclose(*_unquantify_allclose_arguments(a, b, rtol, atol),
-> 1762                        **kwargs)
   1763 
   1764 

<__array_function__ internals> in allclose(*args, **kwargs)

~/anaconda3/envs/sdc/lib/python3.7/site-packages/numpy/core/numeric.py in allclose(a, b, rtol, atol, equal_nan)
   2157 
   2158     """
-> 2159     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
   2160     return bool(res)
   2161 

<__array_function__ internals> in isclose(*args, **kwargs)

~/anaconda3/envs/sdc/lib/python3.7/site-packages/numpy/core/numeric.py in isclose(a, b, rtol, atol, equal_nan)
   2252     # This will cause casting of x later. Also, make sure to allow subclasses
   2253     # (e.g., for numpy.ma).
-> 2254     dt = multiarray.result_type(y, 1.)
   2255     y = array(y, dtype=dt, copy=False, subok=True)
   2256 

<__array_function__ internals> in result_type(*args, **kwargs)

TypeError: invalid type promotion
```

### CODE REVIEW

**Comment by pllim** [comment]
How exactly did you install astropy into the testing environment and what version? How did you run the tests?

**Comment by DeltiKron** [comment]
Hey thanks for your quick reply!

I basically used my day-to-day working version of astropy  (v4.0) which I installed via conda a couple of weeks ago. I ran the tests in an ipython shell by just copy and pasting the two lines from the [coordinates README](https://github.com/astropy/astropy-data/tree/gh-pages/coordinates)

I just went through the astropy developer documentation and noticed that running `astropy.test()` also doesn't work for me. I'll make a fresh install from the source code in a clean environment and get back to you.

**Comment by DeltiKron** [comment]
Ok, so did a fresh install in an empty environment with a freshly cloned astropy install. `astropy.tests()` finishes but the individual sites tests still fail with the same error.

I'm running astropy v4.1 and numpy v1.18.1, I've attached the results of `conda list` below.

[test_env.txt](https://github.com/astropy/astropy-data/files/4254441/test_env.txt)

Any ideas?

**Comment by DeltiKron** [comment]
So one more update: I jumped into the code and narrowed down the problem to the way the test actually checks if two locations are close. Somehow the way `EarthLocation` stores coordinates is not compatible with the testing function that is used to check whether the downloaded and builtin site coordinates match. The function doesn't run through if you compare an `EarthLocation` with itself which means the tests cant' really run through anyway. 

If we only pass the geocentric coordinates from `EarthLocation.geocentric` to the function everything works, including my added site description.

**Comment by pllim** [comment]
@DeltiKron , that sounds like a bug in the tests. Can you please open an issue over at https://github.com/astropy/astropy/issues if you have not done so already? Thanks!

**Comment by DeltiKron** [comment]
just did [that](https://github.com/astropy/astropy/issues/9988), I also submitted a [PR](https://github.com/astropy/astropy/pull/9986) with the code that got the functions running again for me

**Comment by pllim** [comment]
Thank you!

**Comment by DeltiKron** [comment]
Ok, so my PR on astropy was accepted yesterday and the tests for sites.json pass now. This means that there's nothing stopping this request form being accepted, right?

**Comment by pllim** [comment]
@DeltiKron , it does need a review from repo maintainer(s). In the meantime, we ask for your patience. Thank you!

**Comment by cjoldelo** [comment]
If possible, please review/approve this pull request! I'd love to be able to call Teide Observatory with EarthLocation.

**Comment by nstarman** [comment]
Hi @cjoldelo. Thanks for the PR. It looks like a few sites have been added and now the json file has conflicts. If you could resolve these conflicts (it may be easiest to rebase), that would be great.

**Comment by dhomeier** [comment]
Thanks again for the contribution @DeltiKron !
The site has also been added independently in #93; could you check if there are any discrepancies to your entry – apart from whether to have it as `teide` or `tenerife`, and a few " offsets in the geographic coordinates?

**Comment by hamogu** [comment]
This has a duplicate in #93. I'm going to combine the information here with that PR and them merge them. I'm sorry we let this linger for so long; we do appreciate people contributing but maintaining this particular part of astropy has somehow slipped through the cracks.

**Pull request closed without merging**
