### PR TITLE
initial import of data for specreduce

### PR DESCRIPTION
**Pull request by tepickering**
This PR adds some data that is generally useful for doing spectroscopic data reduction. This includes line lists, spectrophotometric standard star data, and atmospheric extinction data for a set of observatories. This is primarily for use by `specreduce`, but could be a generally useful centralized resource for any spectroscopic data reduction/analysis system.

### CODE REVIEW

**Comment by bsipocz** [comment]
Do you really need 620 files added for the library to fully function? What's the policy of curating, updating, etc these files? Is really `astropy-data` the right place for this? The files are small, even the total is not too much, so I don't see the reasoning why this is not packages up in specreduce. 

cc @eteq

**Comment by tepickering** [comment]
my thinking is that a lot of this data already sits in a bunch of different, obscure places and there is value in collecting it all in one place. the value of having it in `astropy-data` vs `specreduce` is that it is then more easily available via the `astropy-data` distribution framework vs having to pull in `specreduce` as a dependency. in fact, making it available via `astropy-data` removes even python as a dependency for getting the data.

policies for curating and updating are TBD. some curation is definitely needed since there is some redundancy and overlap. however, that's a big job. putting everything in now and trimming later at least puts a modicum of provenance into the commit history...

**Comment by bsipocz** [comment]
>  in fact, making it available via astropy-data removes even python as a dependency for getting the data.

I fail to see why would it be more difficult to access the data stored in specreduce/data than in astropy-data/specreduce 🤷‍♀ 

> my thinking is that a lot of this data already sits in a bunch of different, obscure places and there is value in collecting it all in one place. the value of having it in astropy-data vs specreduce is that it is then more easily available via the astropy-data distribution framework vs having to pull in specreduce as a dependency

See the issues around the sites.json file, tons of open PRs, that are open for years as there is no curation for that file. See the recurring issues that are related to remote data, and caching of that remote data on clusters, etc.

**Comment by tepickering** [comment]
> > in fact, making it available via astropy-data removes even python as a dependency for getting the data.
> 
> I fail to see why would it be more difficult to access the data stored in specreduce/data than in astropy-data/specreduce 🤷‍♀

an advantage of `astropy-data` is that it's already set up to be accessed via github pages and can be optimized for CDN. could set up something similar for the `specreduce` repo, but it's a job.

> 
> > my thinking is that a lot of this data already sits in a bunch of different, obscure places and there is value in collecting it all in one place. the value of having it in astropy-data vs specreduce is that it is then more easily available via the astropy-data distribution framework vs having to pull in specreduce as a dependency
> 
> See the issues around the sites.json file, tons of open PRs, that are open for years as there is no curation for that file. See the recurring issues that are related to remote data, and caching of that remote data on clusters, etc.

my expectation is that the `specreduce` reference data will evolve quickly at the start, but level out as it matures. standard star spectra, for example, shouldn't change over time, though new ones may get added from time to time.

**Comment by bsipocz** [comment]
> my expectation is that the specreduce reference data will evolve quickly at the start

keep it in specreduce then while it's evolving. 🤷‍♀ 

Btw, there is hardly any info about the content of these files, their sources, how they were generated. That is not OK. Comment like `Generally grabbed from the Internet. Buyer beware` is not suitable for a well curated dataset that should live in astropy-data.
Yes, it's work, but presumable the aim is not about building a black box, but reproducible science.

**Comment by tepickering** [comment]
well, there are readme files in many cases that describe where they're from and they can be fleshed out as needed if there are specific issues/questions. a big chunk was lifted directly from IRAF and left unchanged in the interest of being able to compare/reproduce what IRAF did with new code.

the deeper problem is that some of those standard star spectra copied over from IRAF have long-standing issues and/or sketchy provenance dating back decades. tracking _that_ down is the big job that's been outstanding for a long time.

**Comment by bsipocz** [comment]
Stating that the source is IRAF is good enough for the iraf line lists, but neither the extinction files, nor the NIST files has any source info but the quote from above, while those should have confirmable canonical sources.

**Comment by tepickering** [comment]
the extinction files were copied over from PypeIt. i will update the README to reflect that. however, where _they_ got them is the deeper question. i know the kpno and ctio ones are from IRAF...

i'll look into the line list provenance...

**Comment by bsipocz** [comment]
they are coming from pypelt is still not reproducible science 🤷‍♀

**Comment by tepickering** [comment]
well, i would argue reproducing what pypeit does with specreduce is exactly one of our goals and using the same reference data is required for that...

**Comment by tepickering** [comment]
that said, i'm updating the readme because i know where the data ultimately comes from and have the references in hand...

**Comment by bsipocz** [comment]
> well, i would argue reproducing what pypeit does with specreduce is exactly one of our goals and using the same reference data is required for that...

That shows a need for a framework to use the files from arbitrary sources (e.g. for testing purposes), rather than redistributing files pulled from third party without source metadata. 

(but as you say you know the references, so there is really no reason not to cite those references)

**Comment by tepickering** [comment]
ok, after a lengthy discussion of various trade-offs, we've decided to make a new `specreduce-data` repo and will put this data there. closing...

**Pull request closed without merging**
