### PR TITLE
update figures for astropy/astropy#10484

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
We seem to be missing a 3.2 build on astropy?

**Comment by astrofrog** [comment]
So unfortunately because the image tests are being used in e.g. 4.1 we now can't change them without making a new timestamp directory. However, you could also simply add a *new* image test with new reference files to avoid having to make a new timestamp directory.

**Review by astrofrog — CHANGES_REQUESTED** [review]
So unfortunately because the image tests are being used in e.g. 4.1 we now can't change them without making a new timestamp directory. However, you could also simply add a new image test with new reference files to avoid having to make a new timestamp directory.

**Comment by Cadair** [comment]
This PR is being backported to 4.1 tho? Anyway I renamed the test, will update here soon.

**Comment by astrofrog** [comment]
@Cadair - yes but 4.1 has shipped so tests in 4.1 need to continue being able to work.

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
