### PR TITLE
Replaced old Chandra event file with a new one

### PR DESCRIPTION
**Pull request by eblur**
This new event file is needed to run the updated FITS-table tutorial

### CODE REVIEW

**Comment by eteq** [comment]
@eblur - can you clarify why this is 75MB while the original is 4MB?  (It's still ok to be 75 if needed, but I just wanted to make sure we know why happened)

**Comment by eblur** [comment]
It's a new file that is a very long observation (160 ks). I didn't realize how large it was.  

I've changed to a shorted 50 ks observation which is only 25 MB now. It's hard to get a satisfying Chandra image without a large number of events.

**Comment by eteq** [comment]
OK, awesome.  One thing about this, @eblur: you'll want to _rebase_ and remove the first commit so that it doesn't end up in the commit history.  If you're not sure how to do this feel free to ask.

**Comment by eblur** [comment]
Okay ... I _think_ I managed to fix this using rebase.

**Comment by eteq** [comment]
Oops, no, this isn't quite right, @eblur.  I think maybe you rebased on the wrong master?

It might be easier if we can resolve this interactively.  Feel free to look for me on google hangouts or sign on to the gitter chat (https://gitter.im/astropy/astropy).

**Comment by eteq** [comment]
(By "isn't quite right", I mean there's a bunch of other commits that are included in this, where there should be just one)

**Comment by eblur** [comment]
Sorry for slow response, I was at the HEAD meeting last week. Let's resolve this issue this week!

**Comment by eteq** [comment]
I should be around and available much of this week, so feel free to try to find me on gitter or google hangouts or whatever, @eblur

**Comment by eteq** [comment]
For the record, this has been successfully rebased through some offline conversation.  The corresponding change to the tutorial itself is astropy/astropy-tutorials#105, so we will want to merge this at the same time as that.

**Pull request merged**
