### PR TITLE
Added WIYN Observatory to sites database

### PR DESCRIPTION
**Pull request by eigenbrot**
A heavily used telescope that deserves its own entry

### CODE REVIEW

**Comment by eteq** [comment]
Thanks @eigenbrot.  Can you confirm that this validated correctly as per these instructions: https://github.com/astropy/astropy-data/blob/gh-pages/coordinates/README.md ?

**Comment by eigenbrot** [comment]
@eteq, yes the site check ran with no errors.

**Comment by shbhuk** [comment]
Just checking regarding this pull request.
Based on https://github.com/astropy/astropy/issues/9618, please change the time zone from Mountain to Arizona

**Comment by pllim** [comment]
Might have been superseded by #81

**Pull request closed without merging**
