### PR TITLE
OCA observatory

### PR DESCRIPTION
**Pull request by majkelx**
+ Observatorio Cerro Armazones

### CODE REVIEW

**Comment by hamogu** [comment]
If I zoom into google maps at the location given, I see mostly empty sand, about half-way between the telescopes and the support buildings:

https://www.google.com/maps/@-24.5951565,-70.1950116,635m/data=!3m1!1e3?entry=ttu

I don't know the observatory, but I wonder if it would be more accurate to set the coordinates to the location of the main telescope (e.g. -24.5893601,-70.1920528)? Or is this coordinate the "average" over several telescopes on the same site? In that case, I would leave it as it is now.

Just reply to this PR and let me know.

**Comment by majkelx** [comment]
Thank you, they were quite off.
I updated the coords to one we are using internally. (also the are in Wikipedia). They are somehow in between of the current main 1.5 and planned 2.5 telescopes, so OK I think.

**Comment by majkelx** [comment]
PS. The coords you provided: (-24.5893601,-70.1920528) are for EELT which is nearby but (unfortunately) not a part of OCA observatory

**Comment by hamogu** [comment]
That's why I ask - I don't know the observatory, all I can do is to have a look at google maps and check if there is actually a structure at the point. I just want to make sure we don't have typos like lat/lon reversed or anything like that.

Thanks for contributing this observatory to the list!

**Comment by majkelx** [comment]
Thank you for your support and checks!

**Pull request merged**
