### PR TITLE
Add intersphinx inventory for requests 2.24

### LINKED ISSUE #100: Add requests intersphinx
Failure for astroquery today:

```
intersphinx inventory 'https://requests.kennethreitz.org/en/stable/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='requests.kennethreitz.org', port=443): Max retries exceeded with url: /en/stable/objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f13742c48d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

### PR DESCRIPTION
**Pull request by pllim**
I grabbed the copy from https://requests.readthedocs.io/en/master/objects.inv . At the time, it was at 2.24.0 .

Fix #100

### CODE REVIEW

**Comment by dhomeier** [comment]
@bsipocz, @pllim, is this still pertinent? requests is at 2.26.0 now.

**Comment by bsipocz** [comment]
@dhomeier - yes, we should update all the intersphinx mirrors here. They only come into play when the main sites are off, and in fact it would be nice to have some more updated versions (though the actual version doesn't really matter).

**Comment by bsipocz** [comment]
btw, maybe it's time to in fact make you and Moritz the website maintainer as finally, something is happening in these repos instead of the usual pushback, and you are the ones doing it.

**Comment by pllim** [comment]
Should I update it to 2.26?

**Comment by dhomeier** [comment]
> btw, maybe it's time to in fact make you and Moritz the website maintainer as finally, something is happening in these repos instead of the usual pushback, and you are the ones doing it.

That was somewhat coincidental really (meaning I cannot guarantee I'll find a lot of time to continue working on it).
But @hamogu and I have resolved to proceed with the outstanding sites updates. ;-)

**Review by bsipocz — APPROVED** [review]
The exact version doesn't matter as these are only needed to provide a backup option in case of the actual sites are not available.

**Pull request merged**
